/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.retodemascota.gui;

import autonoma.retodemascota.main.Park;
import java.awt.Graphics;

/**
 *
 * @author Maria Paz Puerta
 */
public class GameWindow extends javax.swing.JFrame {

    private Park park;

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitGame()
    {
        System.exit(0);
    }
    
    public void setPark(Park park) {
        this.park = park;
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); 
    
       park.draw(g);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GameWindow window = new GameWindow();
        
        Park park = new Park(0, 0, window.getWidth(), window.getHeight());
        
        window.setPark(park);
        
        window.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
